# notify.py
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Sequence

import requests
from SES import AmazonSES


def notify_console(title: str, body: str) -> None:
    print("=" * 80)
    print(title)
    print(body)
    print("=" * 80)


def notify_slack(webhook_url: str, title: str, body: str) -> None:
    if not webhook_url:
        return
    payload = {"text": f"*{title}*\n{body}"}
    r = requests.post(
        webhook_url,
        data=json.dumps(payload),
        headers={"Content-Type": "application/json"},
        timeout=20,
    )
    r.raise_for_status()


def _build_alert_html(
    title: str, body_text: str, image_paths: Sequence[Path] | None
) -> str:
    """
    HTML body that embeds images inline using cid:<filename>.
    Your AmazonSES method will rewrite cid:filename -> cid:<generated>.
    """
    imgs_html = ""
    if image_paths:
        blocks = []
        for p in image_paths:
            p = Path(p)
            # use placeholder cid:filename
            blocks.append(
                f"""
                <div style="margin:16px 0;">
                  <div style="font-size:13px;color:#555;margin-bottom:6px;">{p.name}</div>
                  <img src="cid:{p.name}" style="max-width:100%;border:1px solid #eee;border-radius:12px;" />
                </div>
                """
            )
        imgs_html = "\n".join(blocks)

    safe_body = body_text.replace("\n", "<br/>")

    return f"""
    <html>
      <body style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial,sans-serif; padding:16px;">
        <h2 style="margin:0 0 8px 0;">{title}</h2>
        <div style="font-size:14px; line-height:1.4; color:#111;">
          {safe_body}
        </div>
        {imgs_html}
        <hr style="margin-top:18px;border:none;border-top:1px solid #eee;" />
        <div style="font-size:12px;color:#777;">
          Generated by NYFed Stress Monitor
        </div>
      </body>
    </html>
    """


def notify_email_ses(
    *,
    region: str,
    access_key: str,
    secret_key: str,
    from_address: str,
    to_addrs: Sequence[str],
    subject: str,
    body_text: str,
    image_paths: Optional[Sequence[Path]] = None,
    charset: str = "UTF-8",
) -> None:
    """
    Sends an email via AWS SES. If image_paths are provided, sends HTML with inline images.
    """
    to_addrs = to_addrs.split(",")
    if not to_addrs:
        return

    ses = AmazonSES(
        region=region,
        access_key=access_key,
        secret_key=secret_key,
        from_address=from_address,
        charset=charset,
    )

    if image_paths:
        html = _build_alert_html(subject, body_text, image_paths=image_paths)
        ses.send_html_email_with_inline_images(
            to_addresses=list(to_addrs),
            subject=subject,
            html_body=html,
            image_paths=[Path(p) for p in image_paths],
        )
    else:
        ses.send_text_email(to_address=to_addrs[0], subject=subject, content=body_text)
